services:
  - type: web
    name: gurubit
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: "Mamunislam4363@"
      - key: PORT
        value: 10000
      - key: MUTE_FIREBASE_WARNINGS
        value: "false"
      - key: DEBUG_WS
        value: "false"
      - key: DEBUG_POLLING
        value: "false"
      - key: DEBUG_SMS
        value: "false"
